name: Backend Tests

on:
  push:
    branches: [main, feature/test-branch-protection]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # TODO : Setup Python 3.11 avec cache pip
      - name: Setup Python 3.11 avec cache pip
        uses: actions/setup-python@v6
        with:
            python-version: '3.11'
            cache: 'pip'


      # TODO : Installez UV avec pip
      - name: Installation de uv avec pip
        run: pip install uv

      # TODO : Installez les d√©pendances (cd backend && uv sync)
      - name: Installation des rqrmts
        working-directory: ./backend   
        run: uv sync    
      # TODO : Lancez les tests
      - name: Lancement des tests
        run: |
                cd backend
                uv run pytest -v --cov
