name: Frontend Tests

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # TODO : Setup Node.js 18 avec cache npm
      - name: Setup Node.js 18 avec cache npm
        uses: actions/setupp-node@v6
        with: 
            node-version: 18
            cache: 'npm'
            cache-dependency-path: frontend/package-lock.json

      # Indice : cache-dependency-path: frontend/package-lock.json

      # TODO : Installez les dépendances (cd frontend && npm ci)
      - name: Installation des dépendances
        working-directory: ./frontend
        run: npm ci
      # TODO : Lancez les tests
      - name: Tests
        working-directory: ./frontend
        run: npm test
      # TODO : Vérifiez le build
      - name: Vérification des builds
        working-directory: ./frontend
        run: npm run build